CREATE TABLE "COUPON" (
	"COUPON_ID"	NUMBER		NOT NULL,
	"CODE"	VARCHAR2(50)		NOT NULL,
	"DISCOUNT_AMOUNT"	NUMBER		NOT NULL,
	"EXPIRE_DATE"	DATE		NOT NULL,
	"MEMBER_ID"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COUPON"."COUPON_ID" IS '쿠폰_고유_아이디';

COMMENT ON COLUMN "COUPON"."CODE" IS '쿠폰_코드';

COMMENT ON COLUMN "COUPON"."DISCOUNT_AMOUNT" IS '할인 금액';

COMMENT ON COLUMN "COUPON"."EXPIRE_DATE" IS '쿠폰 만료일';

COMMENT ON COLUMN "COUPON"."MEMBER_ID" IS '쿠폰 소유자';

CREATE TABLE "MOVIE_TYPE" (
	"Key"	VARCHAR(255)		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL,
	"IMAX"	VARCHAR2(10)		NOT NULL,
	"SCREENX"	VARCHAR2(10)		NOT NULL,
	"4DX"	VARCHAR2(10)		NOT NULL,
	"3D"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "MOVIE_TYPE"."MOVIE_ID" IS '고유 영화 식별자';

COMMENT ON COLUMN "MOVIE_TYPE"."IMAX" IS 'IMAX 관';

COMMENT ON COLUMN "MOVIE_TYPE"."SCREENX" IS 'SCREENX관';

COMMENT ON COLUMN "MOVIE_TYPE"."4DX" IS '4DX관';

COMMENT ON COLUMN "MOVIE_TYPE"."3D" IS 'SCREENX관';

CREATE TABLE "MOVIE" (
	"MOVIE_ID"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(100)		NOT NULL,
	"DIRECTOR"	VARCHAR2(50)		NULL,
	"ACTOR"	VARCHAR2(200)		NULL,
	"GENRE"	VARCHAR2(50)		NULL,
	"RUNTIME"	NUMBER(3)		NULL,
	"RELEASE_DATE"	DATE		NOT NULL,
	"RATING"	VARCHAR2(10)		NULL,
	"POSTER_URL"	VARCHAR2(255)		NULL,
	"MOVIE_CREATE"	DATE		NULL,
	"DESCRIPTION"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "MOVIE"."MOVIE_ID" IS '고유 영화';

COMMENT ON COLUMN "MOVIE"."TITLE" IS '영화 제목';

COMMENT ON COLUMN "MOVIE"."DIRECTOR" IS '영화 감독';

COMMENT ON COLUMN "MOVIE"."ACTOR" IS '영화 배우';

COMMENT ON COLUMN "MOVIE"."GENRE" IS '영화 장르';

COMMENT ON COLUMN "MOVIE"."RUNTIME" IS '분단위';

COMMENT ON COLUMN "MOVIE"."RELEASE_DATE" IS '개봉일';

COMMENT ON COLUMN "MOVIE"."RATING" IS '관련 등긍(예:12세)';

COMMENT ON COLUMN "MOVIE"."POSTER_URL" IS '포스터 이미지 주소';

COMMENT ON COLUMN "MOVIE"."MOVIE_CREATE" IS '생성일';

COMMENT ON COLUMN "MOVIE"."DESCRIPTION" IS '영화설명';

CREATE TABLE "THEATER" (
	"THEATER_ID"	NUMBER		NOT NULL,
	"REGION"	VARCHAR2(50)		NOT NULL,
	"NAME"	VARCHAR2(100)		NOT NULL,
	"DESCRIPTION"	VARCHAR2(255)		NULL,
	"Field"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "THEATER"."THEATER_ID" IS '고유 극장 식별자';

COMMENT ON COLUMN "THEATER"."REGION" IS '극장지역';

COMMENT ON COLUMN "THEATER"."NAME" IS '지점 이름';

COMMENT ON COLUMN "THEATER"."DESCRIPTION" IS '극장 소개';

CREATE TABLE "RESERVATION" (
	"RERSERVATION_ID"	NUMBER		NOT NULL,
	"MEMBER_ID"	NUMBER		NOT NULL,
	"SCHEDULE_ID"	NUMBER		NOT NULL,
	"SEAT_NUMBER"	VARCHAR2(10)		NOT NULL,
	"PAYMENT_STATUS"	VARCHAR2(20)		NOT NULL,
	"PAYMENT_DATE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "RESERVATION"."RERSERVATION_ID" IS '예매 고유 식별자';

COMMENT ON COLUMN "RESERVATION"."MEMBER_ID" IS '유저 식별자';

COMMENT ON COLUMN "RESERVATION"."SCHEDULE_ID" IS '상영스케줄 고유 ID';

COMMENT ON COLUMN "RESERVATION"."SEAT_NUMBER" IS '좌석 정보(예:A5)';

COMMENT ON COLUMN "RESERVATION"."PAYMENT_STATUS" IS '완료/대기';

COMMENT ON COLUMN "RESERVATION"."PAYMENT_DATE" IS '결제한 날짜';

CREATE TABLE "INQUIRY" (
	"INQUIRY_ID"	NUMBER		NOT NULL,
	"MEMBER_ID"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(200)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"REG_DATE"	DATE		NOT NULL,
	"STATUS"	VARCHAR2(20)		NULL
);

COMMENT ON COLUMN "INQUIRY"."INQUIRY_ID" IS '1:1 문의 고유 ID';

COMMENT ON COLUMN "INQUIRY"."MEMBER_ID" IS '문의 작성자';

COMMENT ON COLUMN "INQUIRY"."TITLE" IS '문의 제목';

COMMENT ON COLUMN "INQUIRY"."CONTENT" IS '문의 내용';

COMMENT ON COLUMN "INQUIRY"."REG_DATE" IS '문의 작성일';

COMMENT ON COLUMN "INQUIRY"."STATUS" IS '답변 대기 / 완료';

CREATE TABLE "PRICE" (
	"PRICE_ID"	NUMBER		NOT NULL,
	"P_MOIVE"	NUMBER(8)		NOT NULL,
	"WEEKEND"	NUMBER(8)		NOT NULL,
	"KIDS"	NUMBER(8)		NOT NULL,
	"AFTERNOON"	NUMBER(8)		NOT NULL,
	"MIDNIGHT"	NUMBER(8)		NOT NULL,
	"P_IMAX"	NUMBER(8)		NOT NULL,
	"P_SCREENX"	NUMBER(8)		NOT NULL,
	"P_4DX"	NUMBER(8)		NOT NULL,
	"P_3D"	NUMBER(8)		NOT NULL
);

COMMENT ON COLUMN "PRICE"."PRICE_ID" IS '가격정보 ID';

COMMENT ON COLUMN "PRICE"."P_MOIVE" IS '영화 기본 가격';

COMMENT ON COLUMN "PRICE"."WEEKEND" IS '주말 추가 가격';

COMMENT ON COLUMN "PRICE"."KIDS" IS '성인 가격에서 뺸 청소년 가격';

COMMENT ON COLUMN "PRICE"."AFTERNOON" IS '오후 추가 가격';

COMMENT ON COLUMN "PRICE"."MIDNIGHT" IS '심야 추가 가격';

COMMENT ON COLUMN "PRICE"."P_IMAX" IS '특별관 가격 가중치';

COMMENT ON COLUMN "PRICE"."P_SCREENX" IS '특별관 가격 가중치';

COMMENT ON COLUMN "PRICE"."P_4DX" IS '특별관 가격 가중치';

COMMENT ON COLUMN "PRICE"."P_3D" IS '특별관 가격 가중치';

CREATE TABLE "SCHEDULE" (
	"SCHEDULE_ID"	NUMBER		NOT NULL,
	"THEATER_ID"	NUMBER		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL,
	"SCREENING_TIME"	TIMESTAMP		NOT NULL,
	"PRICE"	NUMBER		NOT NULL,
	"IS_MORNING"	NUMBER(1)		NOT NULL,
	"IS_NIGHT"	NUMBER(1)		NOT NULL,
	"IS_AVAILABLE"	NUMBER(1)		NOT NULL
);

COMMENT ON COLUMN "SCHEDULE"."SCHEDULE_ID" IS '상영스케줄 고유 ID';

COMMENT ON COLUMN "SCHEDULE"."THEATER_ID" IS '고유 극장 식별자';

COMMENT ON COLUMN "SCHEDULE"."MOVIE_ID" IS '고유 영화';

COMMENT ON COLUMN "SCHEDULE"."SCREENING_TIME" IS '상영시작일시';

COMMENT ON COLUMN "SCHEDULE"."PRICE" IS '기본가격';

COMMENT ON COLUMN "SCHEDULE"."IS_MORNING" IS 'Y또는N';

COMMENT ON COLUMN "SCHEDULE"."IS_NIGHT" IS 'Y또는N';

COMMENT ON COLUMN "SCHEDULE"."IS_AVAILABLE" IS 'Y또는N';

CREATE TABLE "NOTICE" (
	"NOTICE_ID"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(200)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"REG_DATE"	DATE		NOT NULL,
	"TYPE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_ID" IS '공지 사항 고유 식별자';

COMMENT ON COLUMN "NOTICE"."TITLE" IS '공지 제목';

COMMENT ON COLUMN "NOTICE"."CONTENT" IS '공지 내용';

COMMENT ON COLUMN "NOTICE"."REG_DATE" IS '공지작성일';

COMMENT ON COLUMN "NOTICE"."TYPE" IS 'FAQ/공지/이벤트';

CREATE TABLE "EVENT" (
	"EVENT_ID"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(200)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
	"TYPE"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "EVENT"."EVENT_ID" IS '이벤트 고유 ID';

COMMENT ON COLUMN "EVENT"."TITLE" IS '이벤트 제목';

COMMENT ON COLUMN "EVENT"."CONTENT" IS '이벤트 내용';

COMMENT ON COLUMN "EVENT"."START_DATE" IS '이벤트 시작일';

COMMENT ON COLUMN "EVENT"."END_DATE" IS '이벤트 종료일';

COMMENT ON COLUMN "EVENT"."TYPE" IS '영화/제휴';

CREATE TABLE "MEMBER" (
	"MEMBER_ID"	NUMBER		NOT NULL,
	"USERNAME"	VARCHAR2(50)		NOT NULL,
	"PASSWORD"	VARCHAR2(50)		NOT NULL,
	"NAME"	VARCHAR2(30)		NOT NULL,
	"DATE"	DATE		NOT NULL,
	"GENDER"	VARCHAR(10)		NOT NULL,
	"PHONE"	VARCHAR2(20)		NOT NULL,
	"GRADE"	VARCHAR2(20)		NULL,
	"ADDRESS"	VARCHAR2(200)		NULL,
	"POINT"	NUMBER(8)		NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '유저 식별자';

COMMENT ON COLUMN "MEMBER"."USERNAME" IS '로그인 ID';

COMMENT ON COLUMN "MEMBER"."PASSWORD" IS '암호화 비밀번호';

COMMENT ON COLUMN "MEMBER"."NAME" IS '사용자 이름';

COMMENT ON COLUMN "MEMBER"."DATE" IS 'YYYY-MM-DD';

COMMENT ON COLUMN "MEMBER"."GENDER" IS '남성/여성';

COMMENT ON COLUMN "MEMBER"."PHONE" IS '- 포함한 휴대폰 번호';

COMMENT ON COLUMN "MEMBER"."GRADE" IS '회원 등급';

COMMENT ON COLUMN "MEMBER"."ADDRESS" IS '상세 주소 포함';

COMMENT ON COLUMN "MEMBER"."POINT" IS 'CJ포인트';

CREATE TABLE "MOVIE_MEDIA" (
	"MEDIA_ID"	NUMBER		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL,
	"MEDIA_TYPE"	VARCHAR2(20)		NOT NULL,
	"MEDIA_URL"	VARCHAR2(200)		NOT NULL,
	"MEDIA_STATUS"	NUMBER(1)		NOT NULL
);

COMMENT ON COLUMN "MOVIE_MEDIA"."MEDIA_ID" IS '미디어 고유 ID';

COMMENT ON COLUMN "MOVIE_MEDIA"."MOVIE_ID" IS '고유 영화';

COMMENT ON COLUMN "MOVIE_MEDIA"."MEDIA_TYPE" IS '트레일러, 스틸컷';

COMMENT ON COLUMN "MOVIE_MEDIA"."MEDIA_URL" IS '영상 또는 이미지 URL';

COMMENT ON COLUMN "MOVIE_MEDIA"."MEDIA_STATUS" IS '개방 상태에 따라 Y 또는 N';

CREATE TABLE "POINT_LOG" (
	"LOG_ID"	NUMBER		NOT NULL,
	"MEMBER_ID"	NUMBER		NOT NULL,
	"AMOUNT"	NUMBER		NOT NULL,
	"REASON"	VARCHAR2(100)		NOT NULL,
	"DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "POINT_LOG"."LOG_ID" IS '포인트 사용 내역 ID';

COMMENT ON COLUMN "POINT_LOG"."MEMBER_ID" IS '유저 식별자';

COMMENT ON COLUMN "POINT_LOG"."AMOUNT" IS '사용/적립 포인트';

COMMENT ON COLUMN "POINT_LOG"."REASON" IS '포인트 사유';

COMMENT ON COLUMN "POINT_LOG"."DATE" IS '적립/사용 날짜';

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	VARCHAR(255)		NOT NULL,
	"MEMBER_ID"	NUMBER		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL,
	"RATING"	NUMBER(1)		NOT NULL,
	"CONTENT"	CLOB		NOT NULL,
	"REG_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "REVIEW"."REVIEW_ID" IS '고유 리뷰 식별자';

COMMENT ON COLUMN "REVIEW"."MEMBER_ID" IS '유저 식별자';

COMMENT ON COLUMN "REVIEW"."MOVIE_ID" IS '고유 영화';

COMMENT ON COLUMN "REVIEW"."RATING" IS '별점 평가';

COMMENT ON COLUMN "REVIEW"."CONTENT" IS '리뷰 내용';

COMMENT ON COLUMN "REVIEW"."REG_DATE" IS '작성 날짜';

CREATE TABLE "SEAT" (
	"SEAT_ID"	NUMBER		NOT NULL,
	"THEATER_ID"	NUMBER		NOT NULL,
	"ROW"	VARCHAR2(5)		NOT NULL,
	"COLUMN"	VARCHAR2(5)		NOT NULL
);

COMMENT ON COLUMN "SEAT"."SEAT_ID" IS '좌석 고유 식별자';

COMMENT ON COLUMN "SEAT"."THEATER_ID" IS '고유 극장 식별자';

COMMENT ON COLUMN "SEAT"."ROW" IS '좌석 행';

COMMENT ON COLUMN "SEAT"."COLUMN" IS '좌석 열';

CREATE TABLE "EVENT_USER" (
	"EVENT_USER_ID"	NUMBER		NOT NULL,
	"MEMBER_ID"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "EVENT_USER"."EVENT_USER_ID" IS '이벤트 신청자 ID';

COMMENT ON COLUMN "EVENT_USER"."MEMBER_ID" IS '유저 식별자';

CREATE TABLE "EVENT_NOOTICE" (
	"EVENT_NOTICE_ID"	NUMBER		NOT NULL,
	"MEMBER_ID"	NUMBER		NOT NULL,
	"EVENT_ID"	NUMBER		NOT NULL,
	"E_NAME"	VARCHAR2(100)		NOT NULL,
	"E_CONTENT"	VARCHAR2(300)		NOT NULL
);

COMMENT ON COLUMN "EVENT_NOOTICE"."EVENT_NOTICE_ID" IS '당첨자 고유 ID';

COMMENT ON COLUMN "EVENT_NOOTICE"."MEMBER_ID" IS '유저 식별자';

COMMENT ON COLUMN "EVENT_NOOTICE"."EVENT_ID" IS '이벤트 고유 ID';

COMMENT ON COLUMN "EVENT_NOOTICE"."E_NAME" IS '당첨자 발표 글 제목';

COMMENT ON COLUMN "EVENT_NOOTICE"."E_CONTENT" IS '당점차 발표 글 내용';

CREATE TABLE "CHAT" (
	"CHAT_ID"	NUMBER		NOT NULL,
	"CHATROOM_ID"	NUMBER		NOT NULL,
	"CHAT_DATE"	DATE		NOT NULL,
	"MESSAGE"	VARCHAR2(900)		NOT NULL,
	"SEND"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "CHAT"."CHAT_ID" IS '채팅ID';

COMMENT ON COLUMN "CHAT"."CHATROOM_ID" IS '채팅방 고유 ID';

COMMENT ON COLUMN "CHAT"."CHAT_DATE" IS '채팅방 ID';

COMMENT ON COLUMN "CHAT"."MESSAGE" IS '관리자와 사용자 채팅 내용';

COMMENT ON COLUMN "CHAT"."SEND" IS '보낸사람';

CREATE TABLE "CHATROOM" (
	"CHATROOM_ID"	NUMBER		NOT NULL,
	"MEMBER_ID"	NUMBER		NOT NULL,
	"ROOM_DATE"	DATE		NOT NULL
);

COMMENT ON COLUMN "CHATROOM"."CHATROOM_ID" IS '채팅방 고유 ID';

COMMENT ON COLUMN "CHATROOM"."MEMBER_ID" IS '유저 식별자';

COMMENT ON COLUMN "CHATROOM"."ROOM_DATE" IS '채팅방 개설일';

ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"COUPON_ID"
);

ALTER TABLE "MOVIE_TYPE" ADD CONSTRAINT "PK_MOVIE_TYPE" PRIMARY KEY (
	"Key"
);

ALTER TABLE "MOVIE" ADD CONSTRAINT "PK_MOVIE" PRIMARY KEY (
	"MOVIE_ID"
);

ALTER TABLE "THEATER" ADD CONSTRAINT "PK_THEATER" PRIMARY KEY (
	"THEATER_ID"
);

ALTER TABLE "RESERVATION" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY (
	"RERSERVATION_ID"
);

ALTER TABLE "INQUIRY" ADD CONSTRAINT "PK_INQUIRY" PRIMARY KEY (
	"INQUIRY_ID"
);

ALTER TABLE "PRICE" ADD CONSTRAINT "PK_PRICE" PRIMARY KEY (
	"PRICE_ID"
);

ALTER TABLE "SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY (
	"SCHEDULE_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"NOTICE_ID"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EVENT_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_ID"
);

ALTER TABLE "MOVIE_MEDIA" ADD CONSTRAINT "PK_MOVIE_MEDIA" PRIMARY KEY (
	"MEDIA_ID"
);

ALTER TABLE "POINT_LOG" ADD CONSTRAINT "PK_POINT_LOG" PRIMARY KEY (
	"LOG_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "SEAT" ADD CONSTRAINT "PK_SEAT" PRIMARY KEY (
	"SEAT_ID"
);

ALTER TABLE "EVENT_USER" ADD CONSTRAINT "PK_EVENT_USER" PRIMARY KEY (
	"EVENT_USER_ID"
);

ALTER TABLE "EVENT_NOOTICE" ADD CONSTRAINT "PK_EVENT_NOOTICE" PRIMARY KEY (
	"EVENT_NOTICE_ID"
);

ALTER TABLE "CHAT" ADD CONSTRAINT "PK_CHAT" PRIMARY KEY (
	"CHAT_ID"
);

ALTER TABLE "CHATROOM" ADD CONSTRAINT "PK_CHATROOM" PRIMARY KEY (
	"CHATROOM_ID"
);

